#Input values - data Vector
seq1 <- c(13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25,25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70)
print(seq1)
paste(cat("-------------------------------------------------","\n"))
#Calculating the Mean of Input data seq1
mean <- mean(seq1)
paste(cat("Mean = ", mean,"\n"))
paste(cat("-------------------------------------------------","\n"))
#Calculating the Median of Input data seq1
uniqueValues = unique(seq1)
frequency = tabulate(match(seq1, unique(seq1)))
colnames <- "frequency"
dataMatrix = matrix(frequency, nrow=length(frequency), dimnames=list(uniqueValues, colnames))
print(dataMatrix)

modeFrequency = max(frequency)
indexesVectorModes = which(frequency == modeFrequency)
paste(cat("--------------","\n"))
paste(cat("Mode/Modes : ",uniqueValues[indexesVectorModes],"\n"))

paste(cat("Number of Mode Present is ",length(indexesVectorModes),"\n"))

if(length(indexesVectorModes)==1)
  paste(cat("This is 1 - singlemodal","\n"))
if(length(indexesVectorModes)==2)
  paste(cat("This is 2 - bimodal","\n"))
if(length(indexesVectorModes)==3)
  paste(cat("This is 3 - trimodal","\n"))
if(length(indexesVectorModes)>3)
  paste(cat("This is ",indexesVectorModes," -modal","\n"))
paste(cat("-------------------------------------------------","\n"))
#Calculating the Midrange = Mean(Max and Min)
midRange = mean(c(max(seq1),min(seq1)))
paste(cat("Mid Range = ", midRange,"\n"))
paste(cat("-------------------------------------------------","\n"))
#Calculating the Quartile Q1 (25%) and Q2 (75%)
quantiles = quantile(seq1)
paste(cat("Quartile Q1 = ", quantiles[2], ", Q3 =",quantiles[4],"\n"))
paste(cat("-------------------------------------------------","\n"))
#Calculating the Five Num 
fiveNumSummary = fivenum(seq1)
paste(cat("Five Number Summary = ", fiveNumSummary, " [min Q1 median Q2 max]","\n"))
paste(cat("-------------------------------------------------","\n"))
#Calculating the Five Number Summary
paste(cat("Summary","\n"))
print(summary(seq1))
paste(cat("-------------------------------------------------","\n"))
paste(cat("Plotting in Boxplot","\n"))
par(mfrow=c(2,2))
boxplot(seq1,range=5,horizontal = TRUE, main="Box Plot")
paste(cat("Plotting in qq Plot","\n"))
qqplot(seq1, c(1:100),xlab='Input', ylab='Frequency', main="Q-Q Plot")
paste(cat("Plotting in q Plot","\n"))
plot(seq1, main="Q Plot")
